In [5]:
pip install torch

     |████████████████████████████████| 119.6 MB 417 kB/s eta 0:00:01
You should consider upgrading via the '/Users/kitamurahiroto/opt/anaconda3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [6]:
import torch

In [7]:
torch.__version__

'1.8.1'

In [10]:
# torch.cuda.get_device_name(0)

In [ ]:
#network root 

In [11]:
import torch

In [12]:
import torch.nn as nn

In [14]:
fc = nn.Linear(3,2)
fc

Linear(in_features=3, out_features=2, bias=True)

In [ ]:
#wight

In [15]:
fc.weight

Parameter containing:
tensor([[ 0.1214, -0.5692,  0.3833],
        [ 0.2849, -0.1440,  0.2709]], requires_grad=True)

In [17]:
fc.bias

Parameter containing:
tensor([ 0.1490, -0.4718], requires_grad=True)

In [ ]:
#seed 固定する

In [19]:
torch.manual_seed(0)

In [20]:
fc = nn.Linear(3,2)

In [21]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [22]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

In [25]:
x = torch.Tensor([1,2,3])
x

tensor([1., 2., 3.])

In [26]:
type(x)

torch.Tensor

In [28]:
x.shape

torch.Size([3])

In [ ]:
#call method

In [29]:
u = fc(x)
u

tensor([-0.8219,  0.0526], grad_fn=<AddBackward0>)

In [ ]:
#not line

In [30]:
import torch.nn.functional as F

In [32]:
#ReLU method
h = F.relu(u)
h

tensor([0.0000, 0.0526], grad_fn=<ReluBackward0>)

In [ ]:
#目的関数＝損失関数　＋　正則化項

In [33]:
#
t = torch.Tensor([[1],[3]])
t

tensor([[1.],
        [3.]])

In [34]:
#predict
y = torch.Tensor([[2],[4]])
y

tensor([[2.],
        [4.]])

In [ ]:
#mean **

In [35]:
F.mse_loss(y,t)

tensor(1.)

In [ ]:
#### nn(torch.nn)          →パラメータをもつ
#### F(torch.nn.functional)→パラメータをもたない

In [ ]:
###dataset 

In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F



In [37]:
import sklearn

In [38]:
from sklearn.datasets import load_breast_cancer

In [41]:
breast_cancer = load_breast_cancer()

In [ ]:
#take

In [54]:
x = breast_cancer['data']
t = breast_cancer['target']

In [55]:
x.shape

(569, 30)

In [56]:
t.shape

(569,)

In [57]:
x = torch.tensor(x, dtype=torch.float32)
t = torch.tensor(t, dtype=torch.int64)

In [58]:
type(x), t.type(t)

TypeError: dtype must be a type, str, or dtype object

In [59]:
x.dtype, t.dtype

(torch.float32, torch.int64)

In [60]:
x.shape, t.shape

(torch.Size([569, 30]), torch.Size([569]))

In [ ]:
#DATA LOADER

In [61]:
dataset = torch.utils.data.TensorDataset(x,t)
dataset

In [62]:
type(dataset)

torch.utils.data.dataset.TensorDataset

In [63]:
dataset[0]

(tensor([1.7990e+01, 1.0380e+01, 1.2280e+02, 1.0010e+03, 1.1840e-01, 2.7760e-01,
         3.0010e-01, 1.4710e-01, 2.4190e-01, 7.8710e-02, 1.0950e+00, 9.0530e-01,
         8.5890e+00, 1.5340e+02, 6.3990e-03, 4.9040e-02, 5.3730e-02, 1.5870e-02,
         3.0030e-02, 6.1930e-03, 2.5380e+01, 1.7330e+01, 1.8460e+02, 2.0190e+03,
         1.6220e-01, 6.6560e-01, 7.1190e-01, 2.6540e-01, 4.6010e-01, 1.1890e-01]),
 tensor(0))

In [ ]:
#sample dataset train: val: test = 60%:20%:20%

In [64]:
n_train = int(len(dataset) *0.6)
n_val = int(len(dataset) * 0.2)
n_val = int(len(dataset) *0.2)
n_test = len(dataset) - n_train - n_val

n_train,n_val,n_test

(341, 113, 115)

In [ ]:
#seed 

In [65]:
torch.manual_seed(0)

In [ ]:
#divice

In [69]:
train, val, test = torch.utils.data.random_split(dataset,[n_train, n_val, n_test])
train, val, test

(<torch.utils.data.dataset.Subset at 0x7fe2b7867070>,
 <torch.utils.data.dataset.Subset at 0x7fe2b7867130>)

In [77]:
len(train), len(test)

(341, 115)

In [78]:
batch_size = 10

In [86]:
train_loader = torch.utils.data.DataLoader(train, batch_size, shuffle=True, drop_last=True)
val_loader = torch.utils.data.DataLoader(val, batch_size)
test_loader = torch.utils.data.DataLoader(test, batch_size)

In [87]:
x, t = next(iter(train_loader))

In [88]:
x.shape

torch.Size([10, 30])

In [89]:
t.shape

torch.Size([10])

In [90]:
x

tensor([[1.6780e+01, 1.8800e+01, 1.0930e+02, 8.8630e+02, 8.8650e-02, 9.1820e-02,
         8.4220e-02, 6.5760e-02, 1.8930e-01, 5.5340e-02, 5.9900e-01, 1.3910e+00,
         4.1290e+00, 6.7340e+01, 6.1230e-03, 2.4700e-02, 2.6260e-02, 1.6040e-02,
         2.0910e-02, 3.4930e-03, 2.0050e+01, 2.6300e+01, 1.3070e+02, 1.2600e+03,
         1.1680e-01, 2.1190e-01, 2.3180e-01, 1.4740e-01, 2.8100e-01, 7.2280e-02],
        [1.1470e+01, 1.6030e+01, 7.3020e+01, 4.0270e+02, 9.0760e-02, 5.8860e-02,
         2.5870e-02, 2.3220e-02, 1.6340e-01, 6.3720e-02, 1.7070e-01, 7.6150e-01,
         1.0900e+00, 1.2250e+01, 9.1910e-03, 8.5480e-03, 9.4000e-03, 6.3150e-03,
         1.7550e-02, 3.0090e-03, 1.2510e+01, 2.0790e+01, 7.9670e+01, 4.7580e+02,
         1.5310e-01, 1.1200e-01, 9.8230e-02, 6.5480e-02, 2.8510e-01, 8.7630e-02],
        [1.3610e+01, 2.4690e+01, 8.7760e+01, 5.7260e+02, 9.2580e-02, 7.8620e-02,
         5.2850e-02, 3.0850e-02, 1.7610e-01, 6.1300e-02, 2.3100e-01, 1.0050e+00,
         1.7520e+00, 1.983

In [91]:
t

tensor([0, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
#############################network train

In [112]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.__version__


'1.8.1'

In [113]:
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
x = breast_cancer['data']
t = breast_cancer['target']


In [114]:
x.shape, t.shape

((569, 30), (569,))

In [115]:
x = torch.tensor(x, dtype=torch.float32)
t = torch.tensor(t, dtype=torch.int64)

In [116]:
dataset = torch.utils.data.TensorDataset(x,t)
dataset


In [117]:
n_train = int(len(dataset) * 0.6)
n_val = int(len(dataset) * 0.2)
N_test = len(dataset) - n_train - n_val


torch.manual_seed(0)


train, val, test = torch.utils.data.random_split(dataset, [n_train, n_val, n_test])

In [118]:
len(train), len(val), len(test)

(341, 113, 115)

In [119]:
batch_size = 10

In [120]:
train_loader = torch.utils.data.DataLoader(train,batch_size, shuffle=True, drop_last=True)
val_loader = torch.utils.data.DataLoader(train,batch_size)
test_loader = torch.utils.data.DataLoader(train,batch_size)

In [121]:
x, t = train[0]

In [122]:
x.shape

torch.Size([30])

In [123]:
t

tensor(1)

In [126]:
x.unsqueeze(0).shape

torch.Size([1, 30])

In [128]:
torch.manual_seed(0)

In [130]:
fc1 = nn.Linear(30,10)
fc2 = nn.Linear(10,2)

In [131]:
x.unsqueeze(0).shape

torch.Size([1, 30])

In [134]:
h = fc1(x.unsqueeze(0))
h

tensor([[  50.9289,  137.7259, -125.6362,  136.7067,  100.7003,  -34.0021,
         -101.2300, -128.9460, -124.8382,  104.6964]], grad_fn=<AddmmBackward>)

In [135]:
h.shape

torch.Size([1, 10])

In [138]:
h = F.relu(h)
h

tensor([[ 50.9289, 137.7259,   0.0000, 136.7067, 100.7003,   0.0000,   0.0000,
           0.0000,   0.0000, 104.6964]], grad_fn=<ReluBackward0>)

In [141]:
h = fc2(h)
h

tensor([[-19.7637,  51.7108]], grad_fn=<AddmmBackward>)

In [143]:
F.softmax(h)
h

<ipython-input-143-d6b540ee8966>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(h)


tensor([[-19.7637,  51.7108]], grad_fn=<AddmmBackward>)

In [147]:
class Net(nn.Module):
    
    def __init__(self):
        super().__init__() 
        self.fc1 = nn.Linear(30,10)
        self.fc2 = nn.Linear(10,2)
        
    def forward(self, x):
        h = self.fc1(x)
        h = F.relu(h)
        h = self.fc2(h)
        
        return h
        
        

In [148]:
torch.manual_seed(0)

net = Net()

In [149]:
net

Net(
  (fc1): Linear(in_features=30, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=2, bias=True)
)

In [151]:
x.unsqueeze(0).shape

torch.Size([1, 30])

In [155]:
# net.forward(x.undqueeze(0))
net(x.unsqueeze(0))

tensor([[22.3667, 57.7020]], grad_fn=<AddmmBackward>)

In [ ]:
##### loss function cross function

In [ ]:
###log softmax = cross function

In [158]:
####
for parameter in net.parameters():
    print(parameter)

Parameter containing:
tensor([[-0.0014,  0.0979, -0.1503, -0.1344, -0.0703,  0.0490, -0.0036,  0.1448,
         -0.0162,  0.0483, -0.0552, -0.0359, -0.1744, -0.1209, -0.0753,  0.0068,
          0.0722,  0.1095, -0.1238, -0.0795,  0.0663,  0.1516, -0.0376,  0.1366,
         -0.0294,  0.0193,  0.1653, -0.1694, -0.1149, -0.0462],
        [-0.0712,  0.1577, -0.1183, -0.0840, -0.1276, -0.1710, -0.1066,  0.1569,
          0.0815,  0.0885,  0.0096, -0.0936,  0.0309, -0.1705, -0.1319, -0.0941,
          0.1152,  0.1070, -0.0810, -0.0066,  0.1168,  0.1815,  0.0725,  0.0247,
          0.1224, -0.1075,  0.0340, -0.1416, -0.1265, -0.0943],
        [ 0.0826,  0.0734, -0.1081,  0.0552,  0.1002, -0.0230,  0.0070,  0.0423,
          0.1133,  0.1753, -0.1407, -0.0669,  0.0718,  0.1513,  0.1589,  0.1611,
          0.0363, -0.1588,  0.0168, -0.1142, -0.1702,  0.1622,  0.1388, -0.1821,
          0.0342, -0.0308, -0.0300, -0.0836,  0.0702, -0.1081],
        [ 0.0669,  0.0923,  0.1307,  0.0683, -0.1807, -0.

In [161]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

In [163]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [ ]:
# for batch in train_loader:
#     print(batch)

In [164]:
batch = next(iter(train_loader))

In [165]:
x, t = batch

In [166]:
x.shape

torch.Size([10, 30])

In [168]:
y = net(x)
y

tensor([[ 16.7533,  45.2751],
        [ 25.5686,  68.4042],
        [ 26.5778,  83.9300],
        [ 10.5523,  27.7361],
        [ 16.9485,  43.4075],
        [ 20.5525,  52.5276],
        [ 45.4391, 156.1529],
        [ 19.3272,  50.0786],
        [ 17.6248,  48.9868],
        [ 18.8306,  48.2004]], grad_fn=<AddmmBackward>)

In [171]:
loss = F.cross_entropy(y, t)
loss

tensor(16.8066, grad_fn=<NllLossBackward>)

In [172]:
net.fc1.weight.grad

In [173]:
net.fc1.bias.grad

In [176]:
optimizer.zero_grad()
loss.backward()

In [181]:
net.fc1.weight.grad

tensor([[ 1.0158e+00,  1.3391e+00,  6.6175e+00,  5.7728e+01,  5.2486e-03,
          5.5237e-03,  6.5775e-03,  3.6207e-03,  8.5953e-03,  3.2870e-03,
          2.5995e-02,  6.8186e-02,  1.8273e-01,  3.0994e+00,  2.8485e-04,
          1.0546e-03,  1.8350e-03,  5.8082e-04,  6.9985e-04,  1.3154e-04,
          1.2012e+00,  1.8693e+00,  7.8983e+00,  8.1097e+01,  7.0528e-03,
          1.3889e-02,  2.0030e-02,  7.6641e-03,  1.3480e-02,  4.3654e-03],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  

In [182]:
optimizer.step()

In [183]:
net.fc1.weight.grad

tensor([[ 1.0158e+00,  1.3391e+00,  6.6175e+00,  5.7728e+01,  5.2486e-03,
          5.5237e-03,  6.5775e-03,  3.6207e-03,  8.5953e-03,  3.2870e-03,
          2.5995e-02,  6.8186e-02,  1.8273e-01,  3.0994e+00,  2.8485e-04,
          1.0546e-03,  1.8350e-03,  5.8082e-04,  6.9985e-04,  1.3154e-04,
          1.2012e+00,  1.8693e+00,  7.8983e+00,  8.1097e+01,  7.0528e-03,
          1.3889e-02,  2.0030e-02,  7.6641e-03,  1.3480e-02,  4.3654e-03],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  

In [184]:
torch.cuda.is_available()

False

In [195]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [196]:
max_epoch = 1

In [197]:
torch.manual_seed(0)
net = Net().to(device)

In [198]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

In [ ]:
####　ネットワークを訓練loop

In [199]:
for eopch in range(max_epoch):
    
    for batch in train_loader:
        #1
        x,t = batch
        x = x.to(device)
        t = t.to(device)
        #2
        y = net(x)

        loss = F.cross_entropy(y,t)
        print(f'loss: {loss}')
        

        optimizer.zero_grad()
        loss.backward()

        optimizer.step()

loss: 16.806604385375977
loss: 3188.808837890625
loss: 0.6884490251541138
loss: 0.6869568824768066
loss: 0.6687623858451843
loss: 0.6955960988998413
loss: 0.6687501668930054
loss: 0.6633249521255493
loss: 0.69804447889328
loss: 0.7352138161659241
loss: 0.709438681602478
loss: 0.6499481797218323
loss: 0.6415844559669495
loss: 0.652747631072998
loss: 0.6223450303077698
loss: 0.5804502367973328
loss: 0.5977975130081177
loss: 0.7566229701042175
loss: 0.6353701949119568
loss: 0.5932738780975342
loss: 0.7609547972679138
loss: 0.6332759857177734
loss: 0.7148119807243347
loss: 0.5935741662979126
loss: 0.6293730735778809
loss: 0.8101435899734497
loss: 0.6336615681648254
loss: 0.6315973997116089
loss: 0.7164894938468933
loss: 0.6730174422264099
loss: 0.6730170249938965
loss: 0.7553771734237671
loss: 0.7846001386642456
loss: 0.6114135980606079


In [200]:
#accuracy
x, t = next(iter(train_loader))

In [201]:
net.cpu()

Net(
  (fc1): Linear(in_features=30, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=2, bias=True)
)

In [202]:
y = net(x)
y

tensor([[-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882],
        [-0.4458, -0.0882]], grad_fn=<AddmmBackward>)

In [203]:
t

tensor([0, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [205]:
F.softmax(y)

<ipython-input-205-a481467c755f>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(y)


tensor([[0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885],
        [0.4115, 0.5885]], grad_fn=<SoftmaxBackward>)

In [209]:
y_label = torch.argmax(y, dim=1)

In [210]:
y_label == t

tensor([False,  True,  True,  True, False,  True, False,  True,  True,  True])

In [212]:
(y_label == t).sum()

tensor(7)

In [213]:
len(t)

10

In [214]:
(y_label == t).sum()/len(t)

tensor(0.7000)

In [218]:
torch.manual_seed(0)
net = Net().to(device)

optimizer = torch.optim.SGD(net.parameters(), lr=0.1)

for eopch in range(max_epoch):
    
    for batch in train_loader:
        #1
        x,t = batch
        x = x.to(device)
        t = t.to(device)
        #2
        y = net(x)
        #accuracy
        y_label = torch.argmax(y, dim=1)
        accuracy = (y_label == t).sum()/len(t)
        print(f'accuracy:{accuracy:.2f}')

        loss = F.cross_entropy(y,t)
#         print(f'loss: {loss}')
        

        optimizer.zero_grad()
        loss.backward()

        optimizer.step()

accuracy:0.80
accuracy:0.50
accuracy:0.60
accuracy:0.60
accuracy:0.80
accuracy:0.50
accuracy:0.70
accuracy:0.70
accuracy:0.50
accuracy:0.30
accuracy:0.40
accuracy:0.90
accuracy:0.80
accuracy:0.70
accuracy:0.80
accuracy:0.90
accuracy:0.80
accuracy:0.40
accuracy:0.70
accuracy:0.80
accuracy:0.40
accuracy:0.70
accuracy:0.50
accuracy:0.80
accuracy:0.70
accuracy:0.30
accuracy:0.70
accuracy:0.70
accuracy:0.50
accuracy:0.60
accuracy:0.60
accuracy:0.40
accuracy:0.30
accuracy:0.80


In [ ]:
##### after svcore result   with torch.no_grad

In [ ]:
# val_loader, test_loader

In [223]:
def calc_accuracy(data_loader):

    with torch.no_grad():
        total = 0
        correct = 0

        for batch in val_loader:
            x, t = batch
            x = x.to(device)
            t = t.to(device)
            y = net(x)

            y_label = torch.argmax(y, dim=1)
            total += len(t)
            correct += (y_label == t).sum()

        accuracy = correct / total
        
    return accuracy

In [224]:
calc_accuracy(val_loader)

tensor(0.6217)

In [225]:
calc_accuracy(test_loader)

tensor(0.6217)